### ISSUE TITLE
Background for columns

### ISSUE THREAD

**Issue by Varstahl** [covertnine/c9-blocks#19]
Is it possible to implement background options (image, color, overlay) for the `c9-blocks/column`? Was trying to style a 4x2 grid from the editor and just found out it's impossible. Thought I'd ask before I start copypasting from the column-selector.

Also, there are 599 typos across the files, where it's spelt `c9-column-innner` with an extra `n`. Caused me quite the chin scratch while trying to debug why the custom style was not applying.

**Edit:** also, not sure if you're aware, but `Full width` column wrecks havoc in the editor since it doesn't take into account the WP admin sidebars. I've bandaided it somehow and it sort of works, but I thought I'd mention it here, lest I forget.

**Comment by covertnine** [comment]
We deliberately kept background controls off of the columns because of the group block integration released with WP 5.3.2, which has full support in our theme if you're using that.

> Edit: also, not sure if you're aware, but Full width column wrecks havoc in the editor since it doesn't take into account the WP admin sidebars. I've bandaided it somehow and it sort of works, but I thought I'd mention it here, lest I forget.

It should? What theme did you use?

It doesn't look quite 'pixel-perfect' cause of the maximum width of available space, but most of the full width column settings should work just fine. Certainly on the frontend--upload a few screen shots and I can take a look at it.

I spent a ton of time getting that right in the backend.

-Tim

**Comment by Varstahl** [comment]
> We deliberately kept background controls off of the columns because of the group block integration released with WP 5.3.2, which has full support in our theme if you're using that.

If we're talking about the "Group" object block it could work in theory, but it allows background colour only, while I need background image + overlay.

Thanks for the pointer, though, at least I know where to go tinkering. It's a bit more generated code but should be easier to handle.

> It should? What theme did you use?

c9-starter. And I'm not talking about pixel perfect, I'm talking of the fact that in the CSS provided to the editor it uses 100vw, we're talking about 500+ pixel overflow. Tested on Chrome, Vivaldi, Firefox, Edge, Internet Explorer, on win and linux. While narrow and wide work relatively fine, full width destroys the editor. Same thing regardless of whether C9 Admin plugin is enabled or not.

> but most of the full width column settings should work just fine. Certainly on the frontend

Absolutely, I was merely talking about the back end.

> upload a few screen shots and I can take a look at it.

![image](https://user-images.githubusercontent.com/284077/75177099-c9475580-5735-11ea-980e-004cb1f341e3.png)

That goes on for about 550 pixels off screen. Less with c9 admin but yeah, you get the gist of it. I've band-aided with a 100% `width` and `max-width` in the `client-editor.css` for minimal effort. Something more sensible would rather be using `calc`, like
```css
.entry-content .container .alignfull,
.entry-content .container [class="wp-block-*"][data-align=full],
.entry-content>.alignfull, .wp-block[data-align=full] {
    /* left admin bar: 160px, right properties bar: 356px */
    width: calc(100vw - 160px - 356px - other margins and paddings);
}
```
That yields better and more consistent results, especially when making custom rules based on the body tags to detect whether the properties bar is open or not, but in my case I'm still tinkering with the c9 components so this solution was a bit overkill, I was only aiming at being able to place blocks without scrolling like a madman.

**Comment by covertnine** [comment]
Aha. I see what you're seeing now.

That's done deliberately because the 'full width' of the inner column would extend beyond the max available space inside of the container there in the backend--and extend edge to edge. WordPress' core cover block was doing this as well, so we modeled it after what we saw WP doing.

If we don't have it extend to the full screen width and go behind the inspector, (Minus the pixel widths of the admin sidebar, collapsed or not) then a user wouldn't see a change in the backend when they click on the alignfull button if they're on a standard laptop screen. (The available space is roughly 1000px or so with admin and sidebars open, and alignfull columns are going to be 100vw-margins/menus.

The way we have it now, shows a more accurate reflection of what the actual frontend will look like if the inner column is set to alignfull because it will be well over 1140 pixels, which requires it to break out of the 1000px container that you have if you're on a standard laptop screen with the browser at full width. 

I thought a lot about this and actually had the plugin closer to what you mentioned, but then users wouldn't see a difference in alignments in the backend going from default container width to alignwide to alignfull.

See below in backend.
![Screen Shot 2020-02-24 at 1 13 24 PM](https://user-images.githubusercontent.com/10245479/75183425-24625380-5708-11ea-85ca-daa96882a1a5.png)

Frontend.
![Screen Shot 2020-02-24 at 1 20 07 PM](https://user-images.githubusercontent.com/10245479/75183574-6e4b3980-5708-11ea-8884-9b3f2b0b2bd6.png)

The editor-styles-wrapper still has its max-width set to be 94% to make space for available controls, so the alignfull columns sometime spill over the outer container in the backend.

I wish there was a better solution for this, but we opted for having actual visual changes display in the backend vs. having nothing happen when clicking the alignfull buttons.

**Comment by Varstahl** [comment]
Reasonable, although even with c9 admin the content never sticks to the full length and still overflows the page width.

As for the topic at hand, I'm currently looking into adding functionalities to the group block as you suggested.

**Comment by covertnine** [comment]
> Reasonable, although even with c9 admin the content never sticks to the full length and still overflows the page width.

It shouldn't overflow the viewport--so if you do see content going outside of the viewport I can fix that, but addressing the screen width for the container width in the backend is a challenge that I'm not sure we can get any closer than what we already have without spending probably 20-30 hours getting the CSS right.

If WP had a full screen editing capability that didn't involve us manually collapsing their admin menu with a plugin, I'm sure we could get this right, but the current editor-styles-wrapper and controls make it very difficult. 

I'm hesitant to spend more time getting that working because I honestly believe that the WP core is going to change to change so much in the coming year that we may be swimming against the stream if we introduce too much custom functionality there with the widths--but I'm of course open to suggestions since we've both struggled with the widths!

Thanks for your help BTW! You're our first official contributor!

**Comment by Varstahl** [comment]
Yeah, I agree, that's the same thing I thought to myself. Sure, I can probably fix that for good (ie. `width: calc(100% + 100px); left: -50px`), with some good visual clues without overflowing anything, but then again I just have to try and have something that my clients wouldn't mistake as errors or bugs in my code, while still working, so I opted for the terrible way out myself.

> Thanks for your help BTW! You're our first official contributor!

You're welcome! There are several little things I'd like to contribute that would allow enhancements and lower code footprint while increasing manageability (ie. submitting the patch to change `class-footer.php` to reduce everything to 1 functions and 14 lines of code total, whitespace and comments included), but I'm currently fighting against a deadline, so I'm hacking things together quickly and can't properly create valid PRs.

Also, I just about now remembered to complete the survey you sent 2 weeks ago… about damn time 🤦‍♂

**Comment by covertnine** [comment]
> You're welcome! There are several little things I'd like to contribute that would allow enhancements and lower code footprint while increasing manageability (ie. submitting the patch to change class-footer.php to reduce everything to 1 functions and 14 lines of code total, whitespace and comments included), but I'm currently fighting against a deadline, so I'm hacking things together quickly and can't properly create valid PRs.

I've got 2-3 small bugs I'm going to fix in the next week or two while I try to finish a few more custom themes--so take your time on that, but I have no problem integrating any of those changes as long as they don't break any of our other themes. (They shouldn't cause they use custom templates for the most part.)

@samirillion may have a few things to say about that class cause that's his baby.

**Comment by Varstahl** [comment]
Well, apparently I'm not the only one looking for that exact thing judging by https://github.com/WordPress/gutenberg/issues/14744. So a customization of the group block doesn't make sense, customization of the column could make sense but would be redundant at that point, whenever the changes go live. I guess I'll have to make do in a horrible way, with images instead of backgrounds and several hacks. Oh, well, what can you do…
