### ISSUE TITLE
Full Width Image Carousel Not Loading Responsive Images

### ISSUE THREAD

**Issue by covertnine** [covertnine/c9-blocks#42]
Found a bug with Image Carousel blocks. When in fullscreen mode with responsive image loading enabled, they're still loading in non HD resolution imagery.

You can see this in action on this page: 
https://wowbao.com/8009-dmb3-promo/

Images are JPG'd and the source images are 144dpi and double the size of 1920x1080 yet they're still loading pixelated images. This is on a site with the big image setting disabled so WordPress allows us to create larger than the 2510px width images.

Yet, this carousel still shows a lower resolution graphic.

-Tim

**Comment by htmercury** [comment]
Are the custom larger images included in the `srcset` attribute? That could be the issue, which can be resolved by increasing the default srcset limit (2048px) using https://developer.wordpress.org/reference/hooks/max_srcset_image_width/ - recommended to use this in the theme code rather than the plugin

Also here's how the image is selected from the provided set of srcset (https://css-tricks.com/responsive-images-youre-just-changing-resolutions-use-srcset/) which is done by the browser (for reference). The current image selected by be debugged by inspecting the image element's `props` then going to the `currentSrc` attribute to see which link the browser chose. Issue might also possibly be related to the browser's implementation of srcset.

**Comment by covertnine** [comment]
That’s a much better solution. You can mark this as resolved!! Thanks Ka. 

-T

**Comment by covertnine** [comment]
Hey,

I removed the max image size, uploaded a new image, killed the caches, and I'm looking at the currentSrc prop and it's serving up a smaller version still.

https://wowbao.com/8009-dmb3-promo/

CurrentSrc is giving me an error now, but it's also simply shown me the wrong images.

currentSrc: [Exception: TypeError: Illegal invocation at HTMLImageElement.r (<anonymous>:1:83)]

This is after  removing the max srcset image. It's outputting the full size image at 3839w now, but it's still loading the 1024px one in the carousel even though it's set to full width and with the new markup... any ideas?

You can review at the same link.

**Comment by htmercury** [comment]
It possibly might be related to the "sizes" attribute which specifies the size of image displayed, so you could try adding some filter that removes the "sizes" attributes or set it to it's default value of "100vw". 
https://make.wordpress.org/core/2015/11/10/responsive-images-in-wordpress-4-4/
"themes should customize the default sizes attribute as needed using the wp_calculate_image_sizes filter."
https://developer.wordpress.org/reference/functions/wp_calculate_image_sizes/ (filter link)
So something like
`// Remove the calculated image sizes`
`add_filter( 'wp_calculate_image_sizes', '__return_false' );`


If not that, then it's probably a browser issue in that the calculated "best" image is determined by the browser based on pixel density and display. Also, the currentSrc is determined and loaded once upon page load. Hope that helps.
